#ansible_become_pass: "{{ lookup('keepass', 'user', 'password') }}"
bootstrap_wait_for_host: no
bootstrap_timeout: 1
### ansible
ansible_user: "user"
ansible_password: "{{ lookup('keepass', 'user', 'password') }}"
ansible_become_password: "{{ lookup('keepass', 'user', 'password') }}"

#User für die ssh session
ansible_ssh_user: "user"
ansible_ssh_pass: "{{ lookup('keepass', 'user', 'password') }}"

#Schaltet das checking aus und verbindet einfach auch wenn sich der key geändert hat
ansible_ssh_common_args: "'-o StrictHostKeyChecking=no'"

bootstrap_user: user
#KeePass password (ansible-vault encrypt_string <password>)
#keepass_dbx: "./database_server.kdbx"
#keepass_psw: !vault |
#          $ANSIBLE_VAULT;0.1;AES256
#          39383436353737303362643136623537323333343536616263346364633862653761303566343834
#          3232633931323430376135373464393866346536396330610a663930646266643562613165363963
#          66623330386430343362646238313161306437353366626231303165656662393234336639313531
#          3937646131663738660a366631393566356431613665336535373833383033343362646161366265
#          6239
keepass_dbx: "./homenet_server_db.kdbx"
keepass_key: "./keyfile_homenet.key"

#geerlingguy.ansible
ansible_install_method: pip

#DanielMueller1309.pihole
ipv4_address_pihole: 192.168.178.11


#geerlingguy.pip
pip_install_packages:
  - bpytop
  - proxmoxer

#DanielMueller1309.proxmox_snapshot
vm_api_token_id: 'ci4pve' # the token to use the api
vm_api_host: 'pve' # hostname of the api host, most same as node
vm_api_user: 'root@pam' # the token to use the api
vm_api_password: "{{ lookup('keepass', 'pveroot', 'password') }}"
vm_vmid: ''
vm_snapname: 'snap-from-ansible'
vm_timeout: 60

#ryandaniels.create-users
users:
  - username: root
    password: "{{ lookup('keepass', 'pveroot_hash', 'password') }}" # mkpasswd --method=SHA-512 --stdin
    update_password: always
    groups: ssh, sudo
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAuMew12jn9S1sWc1bCNcPbi1lmEbKSdEoxzKHRlO3IOMivDUUIqmqjaml7ZPun7hL+sBCEVSyKiCr5wNR+VWY6e0p/7E3iDlSlD2fpymff1yWqvsnEmzBnRPGUQdpbGmfNciDt+XnF+nvQgxPBf30BR2//cSBeVpXA1289q0mbc8Z7hDctLjvM43NwjHg0g5KSLx8yXL4VVRg0S/e05azyA7IvQFTf2gVu5NC/rKpI8bs63KMJOR5LTDEYq8V7IlrsBjqTihl+gkXK08x9bqYPWucV3Zg3VGtKcun0WvSmNZPLZ2q5uq+VQFrfv7ioqZVur0XLX78fC9Se+1aC/+Mr0YAdle1P3yenUYFXntTIpI9ID9/EiV0x1cW6dreUy98fVjYmriaXeOK3AxkupQq34aEqXgN8/EH7bJfevvlPYf2JlBIr14MovlIN7zU2sJ2xxQ5jg3H8U2datWwgHoOKt9PAJ7eMsiITUe3310RRQcvkZ/vGHI07ZGfNfleC4fBXcLt+mwaup6rq7pgR+7FMICPiEOn21ektScatVRXGTx47JsMS7YjmAY1qOlUoQC8FXQ8Vp7wunitar6WY45iGTZTDnujkhQfZkllXmpzi8OK0cRwPYfyNPMxaadTY9B9U6CMxjpFV3iq5XgrhhOgtIZfCkW9cX5A7XXy0xXdvQ== user@Acer5

    exclusive_ssh_key: yes
    use_sudo: yes
    use_sudo_nopass: yes
    user_state: present
    servers:
      - proxmox

  - username: user
    password: "{{ lookup('keepass', 'user_hash', 'password') }}" # mkpasswd --method=SHA-512 --stdin
    update_password: always
    groups: ssh, sudo, user
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAuMew12jn9S1sWc1bCNcPbi1lmEbKSdEoxzKHRlO3IOMivDUUIqmqjaml7ZPun7hL+sBCEVSyKiCr5wNR+VWY6e0p/7E3iDlSlD2fpymff1yWqvsnEmzBnRPGUQdpbGmfNciDt+XnF+nvQgxPBf30BR2//cSBeVpXA1289q0mbc8Z7hDctLjvM43NwjHg0g5KSLx8yXL4VVRg0S/e05azyA7IvQFTf2gVu5NC/rKpI8bs63KMJOR5LTDEYq8V7IlrsBjqTihl+gkXK08x9bqYPWucV3Zg3VGtKcun0WvSmNZPLZ2q5uq+VQFrfv7ioqZVur0XLX78fC9Se+1aC/+Mr0YAdle1P3yenUYFXntTIpI9ID9/EiV0x1cW6dreUy98fVjYmriaXeOK3AxkupQq34aEqXgN8/EH7bJfevvlPYf2JlBIr14MovlIN7zU2sJ2xxQ5jg3H8U2datWwgHoOKt9PAJ7eMsiITUe3310RRQcvkZ/vGHI07ZGfNfleC4fBXcLt+mwaup6rq7pgR+7FMICPiEOn21ektScatVRXGTx47JsMS7YjmAY1qOlUoQC8FXQ8Vp7wunitar6WY45iGTZTDnujkhQfZkllXmpzi8OK0cRwPYfyNPMxaadTY9B9U6CMxjpFV3iq5XgrhhOgtIZfCkW9cX5A7XXy0xXdvQ== user@Acer5

    exclusive_ssh_key: yes
    use_sudo: yes
    use_sudo_nopass: yes
    user_state: present
    servers:
      - proxmox
      - ubuntu

  - username: daniel
    password: "{{ lookup('keepass', 'daniel_hash', 'password') }}" # mkpasswd --method=SHA-512 --stdin
    update_password: always
    groups: ssh, sudo, user
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAuMew12jn9S1sWc1bCNcPbi1lmEbKSdEoxzKHRlO3IOMivDUUIqmqjaml7ZPun7hL+sBCEVSyKiCr5wNR+VWY6e0p/7E3iDlSlD2fpymff1yWqvsnEmzBnRPGUQdpbGmfNciDt+XnF+nvQgxPBf30BR2//cSBeVpXA1289q0mbc8Z7hDctLjvM43NwjHg0g5KSLx8yXL4VVRg0S/e05azyA7IvQFTf2gVu5NC/rKpI8bs63KMJOR5LTDEYq8V7IlrsBjqTihl+gkXK08x9bqYPWucV3Zg3VGtKcun0WvSmNZPLZ2q5uq+VQFrfv7ioqZVur0XLX78fC9Se+1aC/+Mr0YAdle1P3yenUYFXntTIpI9ID9/EiV0x1cW6dreUy98fVjYmriaXeOK3AxkupQq34aEqXgN8/EH7bJfevvlPYf2JlBIr14MovlIN7zU2sJ2xxQ5jg3H8U2datWwgHoOKt9PAJ7eMsiITUe3310RRQcvkZ/vGHI07ZGfNfleC4fBXcLt+mwaup6rq7pgR+7FMICPiEOn21ektScatVRXGTx47JsMS7YjmAY1qOlUoQC8FXQ8Vp7wunitar6WY45iGTZTDnujkhQfZkllXmpzi8OK0cRwPYfyNPMxaadTY9B9U6CMxjpFV3iq5XgrhhOgtIZfCkW9cX5A7XXy0xXdvQ== user@Acer5 #laptop
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6T+0INEK2yrT41C0tE5wTYlM1UOj4XrXNLX2lvH4/RoYOjVFICQyh61uryL+Fk9/Lx26Bz7gCyyb+2wRdWr9oEebvzfeg8TFutnB93QRCtebcjY5TJLEoUEyNLznDxYKbZvE4eycH9YKoL6ZTecIa2dSmxp1CmBOONbTMxntrVcDthggpNyPYUKPqUuZ2xpzqZm/fTXrwXpLJOdtbTHqhtSSDkwNQqc/XboD6nUemns5r2xgwuWHAgkSFMFvv2GDsqJPNeOxe399FNLBLupumqQpj9Fp8Rc6EHNyFwAx0LJq/3LUpj5W8XNJYxQP4RG9UDvT5oR2ZfW0kDB6YFZhsqFQyEKNdy9FB/IQ+GzvSpX1/mflDR9sllIexWr+eydhY3OUHFvlE1KMtYFDtsjeLOgBjUWXuEZB7trbvbcjl8Yf/jVmB1qm+jxZh6RTfRa1k1DBVjSml0QSi+omv9uCRt7SqPJzPw/iQC50fdEC6DAr4MkrnoDOqPWYhEmOwJauc0BgcVaaF0TVjLpVfiQDVwBfUO66zlGhJmu0QjJ+t/Yz2MmA4Izmm2H5cwrAG344er44GyprbgCYz4OBoui6vwF+UcwH74sZtKYzNAWNRgH2mL0JrfX7NMM54son2I7qLiwj1qc+hv/ZRIgP0lHTNJtNsidrrmfLnXty40Eh6Zw== u0_a340@localhost #mobile
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCYskKuVPHA4T/5iprUlIePZgA6CLEnayXaDzMUkV0Pzo4H0dIEbmKpnMZBVy6LI6wgSpNYvpn+IO+lL84K1w/NqQNh6DmslnQz3ODwo5Mf+hoCwC7HuJ3an+QobHPQ6FNu7+BMBcFRZjbgnpcUDFgco77fihIhqKj+92deU05Q40AmPbQvpHOioFQIFyR84ZsZVn+P4R2Ip1HhHETgHe5trTQI8MSR5UgF9wlAzS1NsWvH3bh+tRdyLyd6dD1ORYsp7aQvcKNUsYni7LgcumCI5IaUECCvaJWDmPGbY9A5kr2D+uxjbJbixGL6qpLTgw2Ygp3MD3+wpO7zbTMZyXAqiIrEmYljCR0cATo7IJF9wTvX5yGHTlED4XqaT9KYPhXpvTlSLPBq6OGTI/LXtLk089g8Tb3HVH5Jgg+7vZkvPQL1RmPgXhreV9uqtry7hsQ6Sp7ffEL8qcuHR4fao5k5ywLLt99xiILZzrg5ABnbrhz8RFXhQD/w+XBsovdjynLHGqH+Y3w3AHbJDq1dQEzQR8IUiLsu+Z1BeCEY0jiRdFKsiFCPzW05tq20hi538xAFSfZTGz65LtCCAdWOBJ7xO1Kp9t3GDLO8wE1e7O60GHOeRzR0PWYypMDVorJ+bUxOu9WFYxrVIWxjU/aThTfZ8BKliTh3nbb0yXb2IbeYww== danie@danie-acer-vm #drvm
    exclusive_ssh_key: yes
    use_sudo: yes
    use_sudo_nopass: yes
    user_state: present
    servers:
      - proxmox
      - ubuntu

# - username: t_user
#   password: "{{ lookup('keepass', 'user_hash', 'password') }}" # mkpasswd --method=SHA-512 --stdin
#   update_password: always
#   groups: ssh, sudo
#   ssh_key: |
#     ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCYskKuVPHA4T/5iprUlIePZgA6CLEnayXaDzMUkV0Pzo4H0dIEbmKpnMZBVy6LI6wgSpNYvpn+IO+lL84K1w/NqQNh6DmslnQz3ODwo5Mf+hoCwC7HuJ3an+QobHPQ6FNu7+BMBcFRZjbgnpcUDFgco77fihIhqKj+92deU05Q40AmPbQvpHOioFQIFyR84ZsZVn+P4R2Ip1HhHETgHe5trTQI8MSR5UgF9wlAzS1NsWvH3bh+tRdyLyd6dD1ORYsp7aQvcKNUsYni7LgcumCI5IaUECCvaJWDmPGbY9A5kr2D+uxjbJbixGL6qpLTgw2Ygp3MD3+wpO7zbTMZyXAqiIrEmYljCR0cATo7IJF9wTvX5yGHTlED4XqaT9KYPhXpvTlSLPBq6OGTI/LXtLk089g8Tb3HVH5Jgg+7vZkvPQL1RmPgXhreV9uqtry7hsQ6Sp7ffEL8qcuHR4fao5k5ywLLt99xiILZzrg5ABnbrhz8RFXhQD/w+XBsovdjynLHGqH+Y3w3AHbJDq1dQEzQR8IUiLsu+Z1BeCEY0jiRdFKsiFCPzW05tq20hi538xAFSfZTGz65LtCCAdWOBJ7xO1Kp9t3GDLO8wE1e7O60GHOeRzR0PWYypMDVorJ+bUxOu9WFYxrVIWxjU/aThTfZ8BKliTh3nbb0yXb2IbeYww== danie@danie-acer-vm
#   exclusive_ssh_key: yes
#   use_sudo: yes
#   use_sudo_nopass: yes
#   user_state: present
#   servers:
#     - proxmox
#     - ubuntu

dotfile_user:
  - username: user
    dotfiles_repo: "https://github.com/DanielMueller1309/dotfiles.git"
    dotfiles_repo_version: master
    dotfiles_repo_accept_hostkey: false
    dotfiles_repo_local_destination: "/home/user/dotfiles"
    dotfiles_home: "/home/user"
    vundle_dest: "/home/user/.vim/bundle/Vundle.vim"
    vundle_plugins_dest: "/home/user/.vim/bundle/"
    dotfiles_files:
      - .bashrc
      - .tmux.conf
      - .gitignore
      - .vimrc

  - username: root
    dotfiles_repo: "https://github.com/DanielMueller1309/dotfiles.git"
    dotfiles_repo_version: master
    dotfiles_repo_accept_hostkey: false
    dotfiles_repo_local_destination: "/root/dotfiles"
    dotfiles_home: "/root"
    vundle_dest: "/root/.vim/bundle/Vundle.vim"
    vundle_plugins_dest: "/home/root/.vim/bundle/"
    dotfiles_files:
      - .bashrc
      - .tmux.conf
      - .gitignore
      - .vimrc

  - username: daniel
    dotfiles_repo: "https://github.com/DanielMueller1309/dotfiles.git"
    dotfiles_repo_version: master
    dotfiles_repo_accept_hostkey: false
    dotfiles_repo_local_destination: "/home/daniel/dotfiles"
    dotfiles_home: "/home/daniel"
    vundle_dest: "/home/daniel/.vim/bundle/Vundle.vim"
    vundle_plugins_dest: "/home/daniel/.vim/bundle/"
    dotfiles_files:
      - .bashrc
      - .tmux.conf
      - .gitignore
      - .vimrc



#save_vpn_keys
tmp_path: '/tmp/keepass_database/'
wg_keys_db: 'wg_keys_wkf.kdbx'
wg_keys_kf: 'keyfile_wg_keys.key'
wg_path: '/etc/wireguard/keys/'
home_path: '/home/user/keepass_database/'
home_path_daniel: '/home/daniel/keepass_database/'
