#ansible_become_pass: "{{ lookup('keepass', 'user', 'password') }}"
bootstrap_wait_for_host: no
bootstrap_timeout: 1
### ansible
ansible_user: "user"
ansible_password: "{{ lookup('keepass', 'user', 'password') }}"
ansible_become_password: "{{ lookup('keepass', 'user', 'password') }}"

#User für die ssh session
ansible_ssh_user: "user"
ansible_ssh_pass: "{{ lookup('keepass', 'user', 'password') }}"

#Schaltet das checking aus und verbindet einfach auch wenn sich der key geändert hat
ansible_ssh_common_args: "'-o StrictHostKeyChecking=no'"

bootstrap_user: user
#KeePass password (ansible-vault encrypt_string <password>)
keepass_dbx: "./database_server.kdbx"
keepass_psw: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39383436353737303362643136623537323333343536616263346364633862653761303566343834
          3232633931323430376135373464393866346536396330610a663930646266643562613165363963
          66623330386430343362646238313161306437353366626231303165656662393234336639313531
          3937646131663738660a366631393566356431613665336535373833383033343362646161366265
          6239
#geerlingguy.ansible
ansible_install_method: pip

#geerlingguy.pip
pip_install_packages:
  - bpytop
#ryandaniels.create-users
users:
  - username: root
    password: "{{ lookup('keepass', 'pveroot_hash', 'password') }}" # mkpasswd --method=SHA-512 --stdin
    update_password: always
    groups: ssh, sudo
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAuMew12jn9S1sWc1bCNcPbi1lmEbKSdEoxzKHRlO3IOMivDUUIqmqjaml7ZPun7hL+sBCEVSyKiCr5wNR+VWY6e0p/7E3iDlSlD2fpymff1yWqvsnEmzBnRPGUQdpbGmfNciDt+XnF+nvQgxPBf30BR2//cSBeVpXA1289q0mbc8Z7hDctLjvM43NwjHg0g5KSLx8yXL4VVRg0S/e05azyA7IvQFTf2gVu5NC/rKpI8bs63KMJOR5LTDEYq8V7IlrsBjqTihl+gkXK08x9bqYPWucV3Zg3VGtKcun0WvSmNZPLZ2q5uq+VQFrfv7ioqZVur0XLX78fC9Se+1aC/+Mr0YAdle1P3yenUYFXntTIpI9ID9/EiV0x1cW6dreUy98fVjYmriaXeOK3AxkupQq34aEqXgN8/EH7bJfevvlPYf2JlBIr14MovlIN7zU2sJ2xxQ5jg3H8U2datWwgHoOKt9PAJ7eMsiITUe3310RRQcvkZ/vGHI07ZGfNfleC4fBXcLt+mwaup6rq7pgR+7FMICPiEOn21ektScatVRXGTx47JsMS7YjmAY1qOlUoQC8FXQ8Vp7wunitar6WY45iGTZTDnujkhQfZkllXmpzi8OK0cRwPYfyNPMxaadTY9B9U6CMxjpFV3iq5XgrhhOgtIZfCkW9cX5A7XXy0xXdvQ== user@Acer5
    exclusive_ssh_key: yes
    use_sudo: yes
    use_sudo_nopass: yes
    user_state: present
    servers:
      - proxmox
  - username: user
    password: "{{ lookup('keepass', 'user_hash', 'password') }}" # mkpasswd --method=SHA-512 --stdin
    update_password: always
    groups: ssh, sudo, user
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAuMew12jn9S1sWc1bCNcPbi1lmEbKSdEoxzKHRlO3IOMivDUUIqmqjaml7ZPun7hL+sBCEVSyKiCr5wNR+VWY6e0p/7E3iDlSlD2fpymff1yWqvsnEmzBnRPGUQdpbGmfNciDt+XnF+nvQgxPBf30BR2//cSBeVpXA1289q0mbc8Z7hDctLjvM43NwjHg0g5KSLx8yXL4VVRg0S/e05azyA7IvQFTf2gVu5NC/rKpI8bs63KMJOR5LTDEYq8V7IlrsBjqTihl+gkXK08x9bqYPWucV3Zg3VGtKcun0WvSmNZPLZ2q5uq+VQFrfv7ioqZVur0XLX78fC9Se+1aC/+Mr0YAdle1P3yenUYFXntTIpI9ID9/EiV0x1cW6dreUy98fVjYmriaXeOK3AxkupQq34aEqXgN8/EH7bJfevvlPYf2JlBIr14MovlIN7zU2sJ2xxQ5jg3H8U2datWwgHoOKt9PAJ7eMsiITUe3310RRQcvkZ/vGHI07ZGfNfleC4fBXcLt+mwaup6rq7pgR+7FMICPiEOn21ektScatVRXGTx47JsMS7YjmAY1qOlUoQC8FXQ8Vp7wunitar6WY45iGTZTDnujkhQfZkllXmpzi8OK0cRwPYfyNPMxaadTY9B9U6CMxjpFV3iq5XgrhhOgtIZfCkW9cX5A7XXy0xXdvQ== user@Acer5
    exclusive_ssh_key: yes
    use_sudo: yes
    use_sudo_nopass: yes
    user_state: present
    servers:
      - proxmox
      - ubuntu

dotfile_user:
  - username: user
    dotfiles_repo: "https://github.com/DanielMueller1309/dotfiles.git"
    dotfiles_repo_version: master
    dotfiles_repo_accept_hostkey: false
    dotfiles_repo_local_destination: "/home/user/dotfiles"
    dotfiles_home: "/home/user"
    vundle_dest: "/home/user/.vim/bundle/Vundle.vim"
    vundle_plugins_dest: "/home/user/.vim/bundle/"
    dotfiles_files:
      - .bashrc
      - .tmux.conf
      - .gitignore
      - .vimrc

  - username: root
    dotfiles_repo: "https://github.com/DanielMueller1309/dotfiles.git"
    dotfiles_repo_version: master
    dotfiles_repo_accept_hostkey: false
    dotfiles_repo_local_destination: "/root/dotfiles"
    dotfiles_home: "/root"
    vundle_dest: "/root/.vim/bundle/Vundle.vim"
    vundle_plugins_dest: "/home/root/.vim/bundle/"
    dotfiles_files:
      - .bashrc
      - .tmux.conf
      - .gitignore
      - .vimrc
