---
  - hosts: all
    roles:
      - { role: mgrote.apt_install_packages, tags: "apt", become: true }
      - { role: DanielMueller1309.pve_vm_snapshot, tags: "snapshot", vm_hostname: "{{ inventory_hostname }}" , vm_snapname: 'after_apt_install__{{ now_time }}'}
