---
  - hosts: all
    roles:
      - { role: geerlingguy.pip, tags: "pip", become: true }
      - { role: DanielMueller1309.pve_vm_snapshot, tags: "snapshot", vm_hostname: "{{ inventory_hostname }}", vm_snapname: 'after_pip__{{ now_time }}'}
