---
  - hosts: ubuntu
    roles:
      - { role: mgrote.qemu_guest_agent, tags: "qemu_gu", become: true }
      - { role: DanielMueller1309.pve_vm_snapshot, tags: "snapshot", vm_hostname: "{{ inventory_hostname }}" , vm_snapname: 'after_qemu_agent_install__{{ now_time }}'}
