---
  - hosts: localhost

    pre_tasks:
      - name: Retrieve entries by title
        debug:
          #var:  item.title
          msg: "{{ item.title }}"
        with_items:
          - "{{ lookup('multi_return_keepass', ['vpnkeys'] , search='tags') }}"
        vars:
          - kp_entry: lookup('multi_return_keepass', {{ ['vpnkeys'] }}, search='tags')
          #lookup('keepass', 'vpnkeys', search='tags')
          #
          #


