- name: pretasks on ansible host
  hosts: localhost
  tasks:
  - name: create folder
    ansible.builtin.file:
      path: /tmp/keypass_database/
      state: directory
      mode: '0755'

- name: collect keys in database
  hosts: pivpn
  tasks:
  - name: get files from dir.
    find:
      path: "/home/user/keys"
    register: datein

  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#managing-file-names-and-path-names
# - name: debug files
#   debug:
#     msg: "{{ item.path | basename }}"
#   with_items: "{{ datein.files }}"

  - name: register keys
    ansible.builtin.slurp:
      src: '/home/user/keys/{{ item.path | basename }}'
    with_items: "{{ datein.files }}"
    register: datei_inhalt
    #no_log: True

  - name: create database
    keepass:
     #database: /home/user/keypass_database/vault.kdbx
     #db_password: "{{ lookup('keepass', 'user', 'password') }}"
      database: /home/user/keypass_database/vault_wkf.kdbx
      keyfile: /home/user/keypass_database/vault_keyfile.key
      state: create

  - name: get keys to pw_file
    keepass:
     #database: /home/user/keypass_database/vault.kdbx
     #db_password: "{{ lookup('keepass', 'user', 'password') }}"
      database: /home/user/keypass_database/vault_wkf.kdbx
      keyfile: /home/user/keypass_database/vault_keyfile.key
      title: "{{ item.invocation.module_args.src | basename}}"
      groupname: vpn_keys
      entry_password: "{{ item.content | b64decode }}"
      state: modify
    with_items: "{{ datei_inhalt.results }}"
    #no_log: True

  - name: Store db_file on ansible host
    ansible.builtin.fetch:
     #src: /home/user/keypass_database/vault.kdbx
      src: /home/user/keypass_database/vault_wkf.kdbx
      dest: /tmp/keypass_database/vault_wkf.kdbx
      flat: yes
   #become: true

  - name: Store keyfile on ansible host
    ansible.builtin.fetch:
      src: /home/user/keypass_database/vault_keyfile.key
      dest: /tmp/keypass_database/vault_keyfile.key
      flat: yes


#- name: posttasks on ansible host
#  hosts: localhost
#  tasks:
#  - name: merge keyfiles
#    ansible.builtin.command:
#      cmd: ""
#      creates:


