---
  - hosts: localhost
    pre_tasks:
      - name: debug keepass entry as hash
        debug:
          msg: "{{ passwort }}"
        vars:
          passwort: "{{ lookup('keepass', 'vpn_keys/.*', 'title') }}"
