---
  - hosts: localhost
    pre_tasks:
      - name: debug keepass entry as hash
        debug:
          msg: "{{ passwort | password_hash('sha512')}}"
        vars:
          passwort: "{{ lookup('keepass', 'daniel', 'password') }}"
